# Generated by Django 5.1.6 on 2025-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0004_rename_price_busroute_price_one_way_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroute',
            old_name='price_one_way',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='students',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='trip_type',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='country',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_days',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_times',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='price_return',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
