# Generated by Django 5.1.6 on 2025-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0005_rename_price_one_way_busroute_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='price',
        ),
        migrations.AddField(
            model_name='busroute',
            name='price_one_way',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busroute',
            name='price_round_trip',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busroute',
            name='destination',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
